environments:
  development:
    branch: develop
    app_name: lpa-frontend-dev
    azure_resource_group: rg-life-psychology
    api_url: https://api-dev.lifepsychology.com.au
    ga_id: G-DEVXXXXXXXX
    halaxy_url: https://halaxy.com/dev-widget
    required_secrets:
      - AZURE_STATIC_WEB_APPS_API_TOKEN
      - VITE_GA_MEASUREMENT_ID
      - VITE_GOOGLE_ADS_ID
      - VITE_GOOGLE_ADS_CONVERSION_LABEL
      - VITE_OPENAI_API_KEY
      - VITE_CHAT_ENABLED
      - VITE_ASSESSMENT_ENABLED
      - VITE_GTM_ID

  staging:
    branch: staging
    app_name: lpa-frontend-staging
    azure_resource_group: rg-life-psychology
    api_url: https://api-staging.lifepsychology.com.au
    ga_id: G-STAGINGXXXX
    halaxy_url: https://halaxy.com/staging-widget
    required_secrets:
      - AZURE_STATIC_WEB_APPS_API_TOKEN
      - VITE_GA_MEASUREMENT_ID
      - VITE_GOOGLE_ADS_ID
      - VITE_GOOGLE_ADS_CONVERSION_LABEL
      - VITE_OPENAI_API_KEY
      - VITE_CHAT_ENABLED
      - VITE_ASSESSMENT_ENABLED
      - VITE_GTM_ID

  production:
    branch: main
    app_name: lpa-frontend-prod
    azure_resource_group: rg-life-psychology
    api_url: https://api.lifepsychology.com.au
    ga_id: G-PRODXXXXXXXX
    halaxy_url: https://halaxy.com/prod-widget
    required_secrets:
      - AZURE_STATIC_WEB_APPS_API_TOKEN
      - VITE_GA_MEASUREMENT_ID
      - VITE_GOOGLE_ADS_ID
      - VITE_GOOGLE_ADS_CONVERSION_LABEL
      - VITE_OPENAI_API_KEY
      - VITE_CHAT_ENABLED
      - VITE_ASSESSMENT_ENABLED
      - VITE_GTM_ID

# Branch to environment mapping
branch_mapping:
  develop: development
  staging: staging
  main: production
  feature/*: development
  bugfix/*: development
  hotfix/*: staging
